// login and signup
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const LOGOUT_EXPIRED_TOKEN = "LOGOUT_EXPIRED_TOKEN"
export const SIGNUP = "SIGNUP"
export const GET_USER = "GET_USER"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const CHANGE_USER_PASSWORD = "CHANGE_USER_PASSWORD"
export const SEND_ACCESS_CODE = "SEND_ACCESS_CODE"

// event
export const GET_EVENT = "GET_EVENT"

// programs
export const GET_PROGRAMS = "GET_PROGRAMS"
export const GET_PROGRAMS_SUCCESS = "GET_PROGRAMS_SUCCESS"
export const GET_PROGRAMS_FAILURE = "GET_PROGRAMS_FAILURE"
export const SAVE_TALK_EVAL = "SAVE_TALK_EVAL"
export const ASK_SEND_QUESTION = "ASK_SEND_QUESTION"

// livestream
export const GET_LIVESTREAM_ROOMS = "GET_LIVESTREAM_ROOMS"
export const GET_LIVESTREAM_ROOMS_SUCCESS = "GET_LIVESTREAM_ROOMS_SUCCESS"
export const GET_LIVESTREAM_ROOMS_FAILURE = "GET_LIVESTREAM_ROOMS_FAILURE"

// exhibitor
export const GET_EXHIBITORS = "GET_EXHIBITORS"
export const GET_EXHIBITORS_SUCCESS = "GET_EXHIBITORS_SUCCESS"
export const GET_EXHIBITORS_FAILURE = "GET_EXHIBITORS_FAILURE"

// sponsor
export const GET_SPONSORS = "GET_SPONSORS"
export const GET_SPONSORS_SUCCESS = "GET_SPONSORS_SUCCESS"
export const GET_SPONSORS_FAILURE = "GET_SPONSORS_FAILURE"

// speaker
export const GET_SPEAKERS = "GET_SPEAKERS"
export const GET_SPEAKERS_SUCCESS = "GET_SPEAKERS_SUCCESS"
export const GET_SPEAKERS_FAILURE = "GET_SPEAKERS_FAILURE"

// abstract
export const GET_ABSTRACTS = "GET_ABSTRACTS"
export const GET_ABSTRACTS_SUCCESS = "GET_ABSTRACTS_SUCCESS"
export const GET_ABSTRACTS_FAILURE = "GET_ABSTRACTS_FAILURE"
export const SAVE_ABSTRACT_EVAL = "SAVE_ABSTRACT_EVAL"

// top menu
export const HIDE_TOP_MENU = "HIDE_TOP_MENU"
export const SHOW_TOP_MENU = "SHOW_TOP_MENU"
export const SET_TOP_MENU_GO_BACK = "SET_TOP_MENU_GO_BACK"
export const SET_TOP_MENU_GO_HOME = "SET_TOP_MENU_GO_HOME"

// general
export const SET_INITIAL = "SET_INITIAL"
